### ISSUE TITLE
Output "empty"

### ISSUE THREAD

**Issue by Mauricio-MN** [Signalsmith-Audio/signalsmith-stretch#4]
I tried using the "process" method to change the time and all that happens is an array of zeros in the output.
It could be due to the fact that it uses GNU G++ as a compiler and not CLang.

                float** insamples = new float*[1];
                insamples[0] = new float[decodedSF.size()];

                for(int i = 0; i < (int)decodedSF.size(); i++){
                    float copysample = ((float)decodedSF[i]) / (float)32768.0F;
                    if( copysample > 1.0F ) copysample = 1.0F;
                    if( copysample < -1.0F ) copysample = -1.0F;

                    insamples[0][i] = copysample;
                }

                float** outputBuff = new float*[1];
                outputBuff[0] = new float[decodedSF.size()];

                stretch.configure(sampleChannels, decodedSF.size(), decodedSF.size()/4);
                stretch.process(insamples, decodedSF.size(), outputBuff, decodedSF.size() - 100);

                stretch.reset();

"decodedSF" is a sf::int16 vector.
"outputBuff" only returns 0 regardless of the size required in the output.
"sampleChannels" is 1.
"decodedSF.size()" é normalmente 320.

**Comment by lucmans** [comment]
There is some pre-roll data in the output, see [this part of the docs](https://signalsmith-audio.co.uk/code/stretch/#how-to-use-latency-starting-and-ending).

I have a function to drop an arbitrary number of samples `drop_samples(int n_samples)`. After constructing my stream, I drop the first `(stretch.outputLatency() + stretch.inputLatency()) * n_channels` samples to get the current output position at the start of the supplied audio.
