### ISSUE TITLE
AudioWorklet/Wasm version

### ISSUE THREAD

**Issue by marcelblum** [Signalsmith-Audio/signalsmith-stretch#8]
Is SignalsmithStretch.js found at https://signalsmith-audio.co.uk/code/stretch/demo/ intended for public use and part of the MIT Licensed codebase? Any documentation available? I'd love to experiment with an AudioWorklet version of this library and it seems you already went through the trouble of compiling the Wasm and setting up a framework to use the worklet. Just wondering if you'd endorse using SignalsmithStretch.js as a starting point or have any thoughts on reusing some or all of that code in a web audio setting.

**Comment by geraintluff** [comment]
Hi!  Sorry, I don't check GitHub issues as often as I should.

There's now an official web release in `web/`, which will remain in sync with the C++ release.  I'll move the online demo over to this soon.
